### ISSUE TITLE
SM3 含中文时与java端结果不一致

### ISSUE THREAD

**Issue by shenchunping** [luckykellan/dart_sm#4]
数据：{"appFlag":"true","currentPage":1,"pageSize":10,"productName":null,"riskClassCode":"全部"}

dart sm3结果：105513af9332bcf2cce70322ccbc24ab49c62b7e46f810487304e26a4102b9b5
java（hutool） sm3结果：752a357baa8645f07233103acf7e4333ae380225ec9287140a9b5697afc545d6

如果数据改为： {"appFlag":"true","currentPage":1,"pageSize":10,"productName":null,"riskClassCode":"06"} ，则完全匹配

**Comment by luckykellan** [comment]
0.1.4版本已解决
