### ISSUE TITLE
sm2 test 通不过啊

### ISSUE THREAD

**Issue by guchengxi1994** [luckykellan/dart_sm#5]
const data = '12345';
    final keypair = SM2.generateKeyPair();
    String privateKey = keypair.privateKey; // 私钥
    String publicKey = keypair.publicKey; // 公钥

    test('加密和解密', (){
      String encryptData = SM2.encrypt(data, publicKey, cipherMode: C1C2C3);
      String decryptData = SM2.decrypt(encryptData, privateKey);
      expect(decryptData, data);
    });

Expected: '12345'
  Actual: ''
   Which: is different. Both strings start the same, but the actual value is missing the following trailing characters: 12345

**Comment by luckykellan** [comment]
测试类漏写了一个参数，不好意思
```dart
test('加密和解密', (){
  String encryptData = SM2.encrypt(data, publicKey, cipherMode: C1C2C3);
  String decryptData = SM2.decrypt(encryptData, privateKey, cipherMode: C1C2C3); // 同样增加cipherMode参数
  expect(decryptData, data);
});
```
